<img src="TechLabs.png">

<h2>Please enter your full name here: Julia Fiutowska </h2> 



<p> This exam will test your knowledge in Artificial Intelligence. </p>
<p> We will test the following: </p>

- Logistic Regressions
- Neural Networks
- Monte Carlo Simulation

# Question 1:
Below is the code to import a standard dataset with breast cancer.
When you run the cell, you will have it stored as the object "data",
and the description of the dataset is printed out for you.

### Your task is to create two models for classifying the diagnosis, and compare the accuracy metrics for the two:
### 1. a) Logistic Regression: 
"sklearn.linear_model" offers good logit classifiers. Because the dataset is fairly small (~500 rows), we suggest that you use the "liblinear" solver for fitting the logit classifier.

Split the dataset into a test and training (30% test / 70% training) dataset and train the model on the training dataset. Then, classify the test dataset, and compute the accuracy, which you can print as an output.

P.S.: We do not expect you to regularize for type 1 or type 2 errors. Your goal is to build models that classify well the diagnosis. Also, we do not expect you to spend hours on feature engineering and/or other things that may or may not improve testing accuracy. A good answer shall just contain a sensible model and the testing accuracy.

In [1]:
import numpy as np

from sklearn import datasets
data = datasets.load_breast_cancer()
print(np.shape(data.data))

(569, 30)


In [2]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [4]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
#dataframe
columns = data.feature_names
df = pd.DataFrame(data.data, columns = columns)
df

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [6]:
#Name target variable y
y = data.target

In [7]:
#Train/Model spit (70/30)
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size= 0.3)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(398, 30) (398,)
(171, 30) (171,)


In [8]:
#Logistic regression

logistic_model = LogisticRegression(solver = 'liblinear').fit(X_train, y_train)
prediction = logistic_model.predict(X_test)
Predict_probabilities = logistic_model.predict_proba(X_test)
logistic_score = logistic_model.score(X_test, y_test)

In [9]:
logistic_score

0.935672514619883

# Print the logit accuracy below:

In [11]:
logitacc = logistic_score
print(f"\ntesting set accuracy with logit is: {logitacc}")


testing set accuracy with logit is: 0.935672514619883


### 1. b) Feedforward Neural Network:
So far, so good. Let's see how a feedforward neural network does for the same task.

Take the same train/test split as in a), and construct the following neural network, which you fit to the data:

In [12]:
import pickle
pickle.loads(b'\x80\x03]q\x00(X\x15\x00\x00\x00Model: "sequential_2"q\x01XA\x00\x00\x00_________________________________________________________________q\x02XA\x00\x00\x00Layer (type)                 Output Shape              Param #   q\x03XA\x00\x00\x00=================================================================q\x04XA\x00\x00\x00dense_5 (Dense)              (None, 30)                930       q\x05XA\x00\x00\x00_________________________________________________________________q\x06XA\x00\x00\x00dense_6 (Dense)              (None, 50)                1550      q\x07XA\x00\x00\x00_________________________________________________________________q\x08XA\x00\x00\x00dense_7 (Dense)              (None, 30)                1530      q\tXA\x00\x00\x00_________________________________________________________________q\nXA\x00\x00\x00dense_8 (Dense)              (None, 1)                 31        q\x0bXA\x00\x00\x00=================================================================q\x0cX\x13\x00\x00\x00Total params: 4,041q\rX\x17\x00\x00\x00Trainable params: 4,041q\x0eX\x17\x00\x00\x00Non-trainable params: 0q\x0fXA\x00\x00\x00_________________________________________________________________q\x10e.')

['Model: "sequential_2"',
 '_________________________________________________________________',
 'Layer (type)                 Output Shape              Param #   ',
 '=================================================================',
 'dense_5 (Dense)              (None, 30)                930       ',
 '_________________________________________________________________',
 'dense_6 (Dense)              (None, 50)                1550      ',
 '_________________________________________________________________',
 'dense_7 (Dense)              (None, 30)                1530      ',
 '_________________________________________________________________',
 'dense_8 (Dense)              (None, 1)                 31        ',
 '=================================================================',
 'Total params: 4,041',
 'Trainable params: 4,041',
 'Non-trainable params: 0',
 '_________________________________________________________________']

### You can use the library keras to contruct the ANN. Since we are dealing with a classification problem, we recommend binary_crossentropy as a loss function.
Choose a reasonable batch size and epoch count and train the model.
### Here again, print the testing dataset accuracy:

In [ ]:
conda install spyder

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [ ]:
conda install tensorflow

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
                                                                               failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow -> python[version='2.7.*|3.7.*|3.6.*|3.5.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
cha

In [ ]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [14]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [15]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(30, activation= 'sigmoid'),
    tf.keras.layers.Dense(50, activation= 'sigmoid'),
    tf.keras.layers.Dense(30, activation= 'sigmoid'),
    tf.keras.layers.Dense(1, activation= "sigmoid")])

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
model.fit(X_train, y_train, epochs=20, batch_size = 32)

Epoch 1/20
13/13 [==============================] - 1s 2ms/step - loss: 0.6862 - accuracy: 0.6610
Epoch 2/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6489 - accuracy: 0.6465
Epoch 3/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6579 - accuracy: 0.6219
Epoch 4/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6483 - accuracy: 0.6351
Epoch 5/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6500 - accuracy: 0.6210
Epoch 6/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6350 - accuracy: 0.6385
Epoch 7/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6427 - accuracy: 0.6076
Epoch 8/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6157 - accuracy: 0.6421
Epoch 9/20
13/13 [==============================] - 0s 2ms/step - loss: 0.6028 - accuracy: 0.6482
Epoch 10/20
13/13 [==============================] - 0s 2ms/step - loss: 0.5993 - accuracy: 0.6250
Epoch 11/20
13/13 [

In [19]:
score = model.evaluate(X_test, y_test, verbose = 2)[1]

6/6 - 0s - loss: 0.3948 - accuracy: 0.8772


In [20]:
ANNacc = score
print(f"\ntesting set accuracy with logit is: {ANNacc}")


testing set accuracy with logit is: 0.8771929740905762


### 1. c) Compare the performance of the neural net with the logit. Which one seems better at the job and why might that be?
Please also comment on which model you would choose to implement in a case like this and why.

In [ ]:
#The first insight which can be derived from the above analysis is that the variables in the models are lineraly correlated
#From the analysis of the above models we can conclude that they yield similar results and it is difficult to assess which one is superior
#Since both models are so similar we would recommend to go with logistic regression as it is easier to interpret and present to higher-ups
#Lastly we should remmember to consider the randomness created by the implementation of the neural network algorithm, once again 
# speaking in favour of logistic regression


# Question 2:
### Your coding skills have gained you a job as an options trader at a successful hedge fund! Congratulations!!

At the first day, your boss comes to you and asks you, whether he should buy a _call option_* with a certain set of characteristics for 1€.

    *A call option gives you the right (but not obligation) to buy a share for a certain strike price. In other words, if the stock price is higher than the strike price, you get the difference, otherwise, you get 0: 
    
    callpayoff = max(stockprice - strikeprice, 0) 

To price the option, you shall build a monte-carlo simulator which generatates _1 000 000_ random walks, each representing the stock price in one year, which is when the option can be expired. By taking the average of these payouts, you will get the expected payout at expiry!

Luckily, your boss has also given you the characteristics and hints for how the stock price moves: 

The stock price follows a student T distribution with 3 degrees of freedom (the rvs function within the t class from scipy.stats package is a great tool for creating random walks with this distribution: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html  ctrl+f "rvs") 

- The stock price today: 69
- Stock returns follow student T distribution with 3 degrees of freedom
- drift of 10% per year 
- volatility of 20%
- strike price of the option is 96

### Build a function that returns the price of the call option, and shows your boss what payout he can expect from the option in order to explain him, whether he should buy it or not.

    P.S.: If you run into trouble on your way, you can always ask for tips from your boss and since he is a nice guy, he will also give a good grade for all attempts!

In [21]:
from scipy.stats import t
import matplotlib.pyplot as plt


array([-0.0227956 , -0.045569  ,  0.28715905, ...,  0.35327124,
       -0.05965702,  0.01140439])

In [22]:
df = 3
random_walks = 1000000
stockprice = 69
drift = 0.10
stdev = 0.20
strikeprice = 96

r = t.rvs(df = df, loc = drift, scale = stdev, size = random_walks)
r

array([ 0.48447621, -0.29276466, -0.04233949, ...,  0.21329856,
        0.7455111 ,  0.18907736])

In [24]:
def __variance_estimate__(df = 3, random_walks = 1000000, drift = 0.1, stdev = 0.2):
    r = t.rvs(df = df, loc = drift, scale = stdev, size = random_walks)
    return r

result = __variance_estimate__()
result

array([ 0.17665394, -0.05585945, -0.07185975, ..., -0.1146471 ,
        0.17949642, -0.1562245 ])

In [26]:
def _payoff_(estimate, stockprice = 69, strikeprice = 96):
    pay = max(stockprice * (i + 1) - strikeprice, 0)
    return pay

def _price_(estimate, stockprice = 69, strikeprice = 96):
    p = stockprice * (i + 1)
    return p

In [30]:
final_price = []
final_payoff = []

for i in result:
    final_payoff.append(_payoff_(i))
    final_price.append(_price_(i))

# Good luck!

Don't forget: google, github and stack overflow are your best friends!
